name: Build APK for Play Store

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        cache: true

    - name: Prepare signing (keystore from secrets)
      shell: bash
      run: |
        if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ]; then
          echo "Preparing keystore from secrets"
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/dompi-upload.jks
          {
            echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}";
            echo "keyPassword=${{ secrets.KEY_PASSWORD }}";
            echo "keyAlias=${{ secrets.KEY_ALIAS }}";
            echo "storeFile=dompi-upload.jks";
          } > android/key.properties
        else
          echo "No signing secrets found, build will use debug signing."
        fi
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk --release --split-per-abi
    
    - name: Build App Bundle
      run: flutter build appbundle --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: dompi-apk
        path: build/app/outputs/flutter-apk/
    
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: dompi-aab
        path: build/app/outputs/bundle/release/

    - name: Get app version from pubspec
      id: version
      shell: bash
      run: |
        ver=$(grep '^version:' pubspec.yaml | awk '{print $2}')
        echo "tag=v${ver}" >> $GITHUB_OUTPUT

    - name: Create GitHub Release and upload assets
      uses: softprops/action-gh-release@v1
      if: ${{ success() }}
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: Dompi ${{ steps.version.outputs.tag }}
        draft: false
        prerelease: false
        files: |
          build/app/outputs/flutter-apk/*.apk
          build/app/outputs/bundle/release/*.aab
