name: Build APK for Play Store

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        cache: true

    - name: Setup Android SDK
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p $ANDROID_HOME/cmdline-tools
        unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "platforms;android-35" "build-tools;35.0.0" "platform-tools"

    - name: Prepare signing (keystore from secrets)
      shell: bash
      run: |
        echo "Checking secrets availability..."
        if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ]; then
          echo "✅ KEYSTORE_BASE64 found"
          echo "Preparing keystore from secrets"
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/dompi-upload.jks
          {
            echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}";
            echo "keyPassword=${{ secrets.KEY_PASSWORD }}";
            echo "keyAlias=${{ secrets.KEY_ALIAS }}";
            echo "storeFile=dompi-upload.jks";
          } > android/key.properties
          echo "✅ Keystore and key.properties created"
          ls -la android/
        else
          echo "❌ KEYSTORE_BASE64 not found - build will fail"
          echo "Available secrets:"
          echo "KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD != '' && 'SET' || 'NOT SET' }}"
          echo "KEY_PASSWORD: ${{ secrets.KEY_PASSWORD != '' && 'SET' || 'NOT SET' }}"
          echo "KEY_ALIAS: ${{ secrets.KEY_ALIAS != '' && 'SET' || 'NOT SET' }}"
        fi
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk --release --split-per-abi
    
    - name: Build App Bundle
      run: flutter build appbundle --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: dompi-apk
        path: build/app/outputs/flutter-apk/
    
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: dompi-aab
        path: build/app/outputs/bundle/release/

    - name: Get app version from pubspec
      id: version
      shell: bash
      run: |
        ver=$(grep '^version:' pubspec.yaml | awk '{print $2}')
        echo "tag=v${ver}" >> $GITHUB_OUTPUT

    - name: Create GitHub Release and upload assets
      uses: softprops/action-gh-release@v1
      if: ${{ success() }}
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: Dompi ${{ steps.version.outputs.tag }}
        draft: false
        prerelease: false
        files: |
          build/app/outputs/flutter-apk/*.apk
          build/app/outputs/bundle/release/*.aab
