name: Build APK for Play Store

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        cache: true

    - name: Prepare signing (keystore from secrets)
      shell: bash
      run: |
        if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ]; then
          echo "Preparing keystore from secrets"
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/dompi-upload.jks
          cat > android/key.properties << 'EOF'
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=../dompi-upload.jks
          EOF
        else
          echo "No signing secrets found, build will use debug signing." 
        fi
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk --release --split-per-abi
    
    - name: Build App Bundle
      run: flutter build appbundle --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: dompi-apk
        path: build/app/outputs/flutter-apk/
    
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: dompi-aab
        path: build/app/outputs/bundle/release/
